// packages/svelte-grid/src/Grid.svelte
<script lang="ts">
  /**
   * egjs-grid
   * Copyright (c) 2021-present NAVER Corp.
   * MIT license
   */
  import { onMount, beforeUpdate, createEventDispatcher, onDestroy, afterUpdate } from "svelte";
  import VanillaGrid, { GRID_EVENTS, GridFunction, GridOptions } from "@egjs/grid";
  export let GridClass: GridFunction;

  const dispatch = createEventDispatcher();
  let container: HTMLElement;
  let grid: VanillaGrid;
  let isFirstMount = false;
  let attributes = {};

  function updateAttributes() {
    attributes = { ...$$props };

    const defaultOptions = GridClass.defaultOptions;

    delete attributes["GridClass"];
    for (const name in defaultOptions) {
      delete attributes[name];
    }
  }

  beforeUpdate(() => {
    updateAttributes();
    if (!grid) {
      return;
    }

    const propertyTypes = GridClass.propertyTypes;
    for (const name in propertyTypes) {
      if (name in $$props) {
        grid[name] = $$props[name];
      }
    }
  });
  onMount(() => {
    const defaultOptions = GridClass.defaultOptions;
    const options: Partial<GridOptions> = {};

    for (const name in defaultOptions) {
      if (name in $$props) {
        (options as any)[name] = $$props[name];
      }
    }

    grid = new GridClass(container!, options);

    GRID_EVENTS.forEach((name) => {
      grid.on(name as any, (e: any) => {
        dispatch(name, e);
      });
    });
    grid.renderItems();
  });
  afterUpdate(() => {
    if (isFirstMount) {
      isFirstMount = false;
      return;
    }
    const propertyTypes = GridClass.propertyTypes;

    for (const name in propertyTypes) {
      if (name in $$props) {
        (grid as any)[name] = ($$props as any)[name];
      }
    }
    grid.syncElements();
  });
  onDestroy(() => {
    grid.destroy();
  });
  export function getInstance() {
    return grid;
  }
</script>

<div bind:this={container} {...attributes}>
  <slot />
</div>

// packages/react-grid/src/Grid.tsx
/**
 * egjs-grid
 * Copyright (c) 2021-present NAVER Corp.
 * MIT license
 */
import * as React from "react";
import VanillaGrid, { withGridMethods, GridOptions, GridMethods, GridFunction } from "@egjs/grid";
import { ReactGridEvents } from "./types";
import { REACT_GRID_EVENTS } from "./consts";

export abstract class Grid<T extends GridOptions>
  extends React.PureComponent<T & ReactGridEvents & { [key: string]: any }> {
  public static GridClass: GridFunction;
  @withGridMethods
  private _grid!: VanillaGrid;
  private _containerRef = React.createRef<HTMLDivElement>();
  public render() {
    const attributes: { [key: string]: any } = {};
    const props = this.props;
    const GridClass = (this.constructor as typeof Grid).GridClass;
    const defaultOptions = GridClass.defaultOptions;

    for (const name in props) {
      if (name in defaultOptions || name in REACT_GRID_EVENTS) {
        continue;
      }
      attributes[name] = props[name];
    }
    return <div ref={this._containerRef} {...attributes}>
      {this.props.children}
    </div>;
  }
  public componentDidMount() {
    const GridClass = (this.constructor as typeof Grid).GridClass;
    const defaultOptions = GridClass.defaultOptions;
    const options: Partial<GridOptions> = {};
    const props = this.props;

    for (const name in defaultOptions) {
      if (name in props) {
        (options as any)[name] = (props as any)[name];
      }
    }

    this._grid = new GridClass(this._containerRef.current!, options);
    this._grid.syncElements();
  }
  public componentDidUpdate() {
    const GridClass = (this.constructor as typeof Grid).GridClass;
    const propertyTypes = GridClass.propertyTypes;
    const props = this.props;
    const grid = this._grid;

    for (const name in propertyTypes) {
      if (name in props) {
        (grid as any)[name] = (props as any)[name];
      }
    }
    this._grid.syncElements();
  }
  public componentWillUnmount() {
    this._grid.destroy();
  }
}
export interface Grid<T extends GridOptions> extends GridMethods<Grid<T>> { }
